# SimpleEffects - https://github.com/karpen-dev/SimpleEffects

# Config version
# Don't change this parameter
config-version: 7.0

# For change color use ampersand and §
# Example &fHello or §fWorld

# Plugin language - en_US, ja_JP
lang: en_US

update:
  using: true
  msg: "&cYou do not have the latest version of the plugin installed. You can download the latest version at https://modrinth.com/plugin/simpleeffects"

# Separate rights
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

  totem_spiral: "karpen.simpleefects.totem_spiral"
  endrod_spiral: "karpen.simpleefects.endrod_spiral"
  cherry_spiral: "karpen.simpleefects.cherry_spiral"
  pale_spiral: "karpen.simpleefects.pale_spiral"
  purple_spiral: "karpen.simpleefects.purple_spiral"
  note_spiral: "karpen.simpleefects.note_spiral"
