# SimpleEffects - https://github.com/karpen-dev/SimpleEffects

# Config version
# Don't change this parameter
config-version: 5.2

# For change color use ampersand and §
# Example &fHello or §fWorld

# Plugin language - ru, en, jp, be
lang: en

# Save method (TXT, MYSQL)
method: TXT

# Waring for flashes effects
# Don't recommend disable this
warning: true

update:
  using: true
  msg: "&cYou do not have the latest version of the plugin installed. You can download the latest version at https://modrinth.com/plugin/simpleeffects"

# If you using mysql, change db config
db:

  # Connection url
  url: "jdbc:mysql://localhost:3306/effects"

  # db username
  username: "root"

  # db user password
  password: "root"

# Separate rights
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

  cloud: "karpen.simpleeffects.cloud"

# Count particle
count:
  cherry: 1
  endrod: 1
  totem: 1
  heart: 1
  pale: 1
  notes: 1
  purple: 1

  # The count of cloud doesn't change

# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# プラグインの翻訳は完璧ではなく、誤りが含まれている可能性があります。
# X: https://x.com/karpen5i5 からのフィードバックをお待ちしております。

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
en:
  enable-effect: "&aEffect enabled"
  disable-effect: "&aEffect disabled"

  menu-name: "Select effect"
  item-enable: "&aEnable this effect"
  item-disable: "&cDisable this effect"

  unsupported-ver: "&cYou are using a version lower than 1.21.4, the some feature not available"
  unsupported-name: "&cDon't supported to you version"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cWhile using this effect you may see flashes and blurry images."

  err-console: "&cYou can't send this command"
  err-perms: "&cYou can't have permission for using this"
  err-args: "&cUsing /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"
  err-command: "&cInvalid command. Use /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"

# Japanese
jp:
  enable-effect: "&aエフェクト有効"
  disable-effect: "&a効果は無効です"

  menu-name: "エフェクトを選択"
  item-enable: "&aこの効果を有効にする"
  item-disable: "&cこの効果を無効にする"

  unsupported-ver: "&c1.21.4より前のバージョンを使用しています。一部の機能はご利用いただけません。"
  unsupported-name: "&cあなたのバージョンではサポートされていません"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cこの効果を使用すると、フラッシュやぼやけた画像が見える場合があります。"

  err-console: "&cこのコマンドは送信できません"
  err-perms: "&cこれを使用する権限がありません"
  err-args: "&c/eff を使用する <cherry | endrod | totem | heart | pale | purple | note | cloud>"
  err-command: "&c無効なコマンドです。/eff <cherry | endrod | totem | heart | pale | purple | note | cloud> を使用してください。"

# Russian
ru:
  enable-effect: "&aЭффект включен"
  disable-effect: "&aЭффект выключен"

  menu-name: "Выбрать эффект"
  item-enable: "&aВключить этот эффект"
  item-disable: "&cВыключить этот эффект"

  unsupported-ver: "&cВы используйте версию сервера ниже 1.21.4, эта функция недоступна"
  unsupported-name: "&cНедоступно на вашей версии"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cПри использовании этого эффекта вы можете увидеть вспышки и размытие изображения."

  err-console: "&cЭту команду может отправлять только игрок"
  err-perms: "&cВы не имейте прав для использования этой команды"
  err-args: "&cИспользуйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>>"
  err-command: "&cНеизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"

# Belarusian
be:
  enable-effect: "&aЭфект уключаны"
  disable-effect: "&aЭфект выключаны"

  menu-name: "Выбраць эфект"
  item-enable: "&aУключыць гэты эфект"
  item-disable: "&cВыключыць гэты эфект"

  unsupported-ver: "&cВы карыстаецеся версію сервера ніжэй 1.21.4, гэтая функцыя недаступная"
  unsupported-name: "&cНедаступна на вашай версіі"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cПры выкарыстанні гэтага эфекту вы можаце выбліскі і размыццё малюнка."

  err-console: "&cГэту каманду можа адпрауляць толькі ігрок"
  err-perms: "&cВы не маеце прау для выкарыставання гэтай каманды"
  err-args: "&cВыкарыстовывайце /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"
  err-command: "&cНевядомая каманда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"