# SimpleEffects - v1.3 https://github.com/karpen-dev/SimpleEffects

# Plugin language - ru, en
# Язык плагина - ru, en
lang: en

# Save method (TXT, MYSQL)
# Метод сохранения (TXT, MYSQL)
method: TXT

# If you using mysql, change db config
# Если вы используйте mysql настройте данные для подключения
db:

  # Connection url
  # Url для подключения к базе
  url: "jdbc:mysql://localhost:3306/effects"

  # db username
  # Пользователь базы
  username: "root"

  # db user password
  # Пароль пользователя базы
  password: "root"

# Separate rights
# Использовать отдельные права
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

# Количество частиц
# Count particle
count:
  cherry: 1
  endrod: 1
  totem: 1
  heart: 1
  pale: 1
  notes: 1
  purple: 1

# Сообщения
# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
en:
  enable-effect: "Effect enabled"
  disable-effect: "Effect disabled"

  err-console: "You can't send this command"
  err-perms: "You can't have permission for using this"
  err-args: "Using /eff <cherry | endrod | totem | heart | pale>"
  err-command: "Invalid command. Use /eff <cherry | endrod | totem | heart | pale>"

# Russian
ru:
  enable-effect: "Эффект включен"
  disable-effect: "Эффект выключен"

  err-console: "Эту команду может отправлять только игрок"
  err-perms: "Вы не имейте прав для использования этой команды"
  err-args: "Используйте /eff <cherry | endrod | totem | heart>"
  err-command: "Неизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale>"