# SimpleEffects - v1.2.5 https://github.com/karpen-dev/SimpleEffects

# Plugin language - ru, en
# Язык плагина - ru, en
lang: en

# Save method (TXT, MYSQL)
# Метод сохранения (TXT, MYSQL)
method: TXT

# If you using mysql, change db config
# Если вы используйте mysql настройте данные для подключения
db:

  # Connection url
  # Url для подключения к базе
  url: "mysql://localhost:3306/effects"

  # db username
  # Пользователь базы
  username: "root"

  # db user password
  # Пароль пользователя базы
  password: "root"

# Количество частиц вишни
# Count cherry particle
count-cherry: 1

# Количество частиц энд род
# Count endrod particle
count-endrod: 1

# Количество частиц тотема
# Count totem particle
count-totem: 1

# Количество частиц сердец
# Count heart particle
count-heart: 0.5

# Количество бледных частиц
# Count pale particle
count-pale: 1

# Сообщения
# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
enable-effect: "Effect enabled"
disable-effect: "Effect disabled"

err-console: "You can't send this command"
err-args: "Using /eff <cherry | endrod | totem | heart | pale>"
err-command: "Invalid command. Use /eff <cherry | endrod | totem | heart | pale>"

# Russian
enable-effect-ru: "Эффект включен"
disable-effect-ru: "Эффект выключен"

err-console-ru: "Эту команду может отправлять только игрок"
err-args-ru: "Используйте /eff <cherry | endrod | totem | heart>"
err-command-ru: "Неизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale>"