# SimpleEffects - v1.1.5.2 https://karpen-dev/simpleeffects

# Plugin language - ru, en
# Язык плагина - ru, en
lang: en

# Количество частиц вишни
# Count cherry particle
count-cherry: 1

# Количество частиц энд род
# Count endrod particle
count-endrod: 1

# Количество частиц тотема
# Count totem particle
count-totem: 1

# Количество частиц сердец
# Count heart particle
count-heart: 0.5

# Сообщения
# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
selected-cherry: "Cherry effect enabled"
selected-endRod: "Endrod effect enabled"
selected-totem: "Totem effect enabled"
selected-heart: "Heart effect enabled"

disable-cherry: "Cherry effect disabled"
disable-endRod: "Endrod effect disabled"
disable-totem: "Totem effect disabled"
disable-heart: "Heart effect disabled"

err-console: "You can't send this command"
err-args: "Using /eff <cherry | endrod | totem | heart>"
err-command: "Invalid command. Use /eff <cherry | endrod | totem | heart>"

# Russian
selected-cherry-ru: "Эффект вишни активирован"
selected-endRod-ru: "Эффект энд род активирован"
selected-totem-ru: "Эффект тотема активирован"
selected-heart-ru: "Эффект сердец активирован"

disable-cherry-ru: "Эффект вишни выключен"
disable-endRod-ru: "Эффект энд род выключен"
disable-totem-ru: "Эффект тотем выключен"
disable-heart-ru: "Эффект сердец выключен"

err-console-ru: "Эту команду может отправлять только игрок"
err-args-ru: "Используйте /eff <cherry | endrod | totem | heart>"
err-command-ru: "Неизвестная команда. Используйте /eff <cherry | endrod | totem | heart>"