# SimpleEffects - v1.4.2 https://github.com/karpen-dev/SimpleEffects

# For change color use ampersand and §
# Example &fHello or §fWorld
# Для выбора цвета используйте & или §
# Например &fHello или §fWorld

# Plugin language - ru, en
# Язык плагина - ru, en
lang: en

# Save method (TXT, MYSQL)
# Метод сохранения (TXT, MYSQL)
method: TXT

# Waring for flashes effects
# Don't recommend disable this
# Предупреждения о резких вспышках
# Не рекомендую отключать это
warning: true

update:
  using: true
  msg: "&cYou do not have the latest version of the plugin installed. You can download the latest version at https://modrinth.com/plugin/simpleeffects"

# If you using mysql, change db config
# Если вы используйте mysql настройте данные для подключения
db:

  # Connection url
  # Url для подключения к базе
  url: "jdbc:mysql://localhost:3306/effects"

  # db username
  # Пользователь базы
  username: "root"

  # db user password
  # Пароль пользователя базы
  password: "root"

# Separate rights
# Использовать отдельные права
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

  cloud: "karpen.simpleeffects.cloud"

# Количество частиц
# Count particle
count:
  cherry: 1
  endrod: 1
  totem: 1
  heart: 1
  pale: 1
  notes: 1
  purple: 1

  # The count of cloud doesn't change
  # Количество частиц для эффекта облака изменять не возможно

# Сообщения
# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
en:
  enable-effect: "&aEffect enabled"
  disable-effect: "&aEffect disabled"

  menu-name: "&aSelect effect"
  item-enable: "&aEnable this effect"
  item-disable: "&cDisable this effect"

  unsupported-ver: "&cYou are using a version lower than 1.21.4, the some feature not available"
  unsupported-name: "&cDon't supported to you version"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cWhile using this effect you may see flashes and blurry images."

  err-console: "&cYou can't send this command"
  err-perms: "&cYou can't have permission for using this"
  err-args: "&cUsing /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"
  err-command: "&cInvalid command. Use /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"

# Russian
ru:
  enable-effect: "&aЭффект включен"
  disable-effect: "&aЭффект выключен"

  menu-name: "&aВыбрать эффект"
  item-enable: "&aВключить этот эффект"
  item-disable: "&cВыключить этот эффект"

  unsupported-ver: "&cВы используйте версию сервера ниже 1.21.4, эта функция недоступна"
  unsupported-name: "&cНедоступно на вашей версии"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  notes: "&3Notes"
  cloud: "&7Cloud"

  # Warning
  warning: "&cПри использовании этого эффекта вы можете увидеть вспышки и размытие изображения."

  err-console: "&cЭту команду может отправлять только игрок"
  err-perms: "&cВы не имейте прав для использования этой команды"
  err-args: "&cИспользуйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>>"
  err-command: "&cНеизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"