# SimpleEffects - v1.4 https://github.com/karpen-dev/SimpleEffects

# Plugin language - ru, en
# Язык плагина - ru, en
lang: en

# Save method (TXT, MYSQL)
# Метод сохранения (TXT, MYSQL)
method: TXT

# Waring for flashes effects
# Don't recommend disable this
# Предупреждения о резких вспышках
# Не рекомендую отключать это
warning: true

update:
  using: true
  msg: "You do not have the latest version of the plugin installed. You can download the latest version at https://modrinth.com/plugin/simpleeffects"

# If you using mysql, change db config
# Если вы используйте mysql настройте данные для подключения
db:

  # Connection url
  # Url для подключения к базе
  url: "jdbc:mysql://localhost:3306/effects"

  # db username
  # Пользователь базы
  username: "root"

  # db user password
  # Пароль пользователя базы
  password: "root"

# Separate rights
# Использовать отдельные права
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

  cloud: "karpen.simpleeffects.cloud"

# Количество частиц
# Count particle
count:
  cherry: 1
  endrod: 1
  totem: 1
  heart: 1
  pale: 1
  notes: 1
  purple: 1

  # The count of cloud doesn't change
  # Количество частиц для эффекта облака изменять не возможно

# Сообщения
# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/karpen5i5

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/karpen5i5

# English
en:
  enable-effect: "Effect enabled"
  disable-effect: "Effect disabled"

  menu-name: "Select effect"
  item-enable: "Enable this effect"
  item-disable: "Disable this effect"

  unsupported-ver: "You are using a version lower than 1.21.4, the some feature not available"
  unsupported-name: "Don't supported to you version"

  cherry: "Cherry"
  endrod: "Endrod"
  totem: "Totem"
  heart: "Heart"
  pale: "Pale"
  purple: "Purple"
  notes: "Notes"
  cloud: "Cloud"

  # Warning
  warning: "While using this effect you may see flashes and blurry images."

  err-console: "You can't send this command"
  err-perms: "You can't have permission for using this"
  err-args: "Using /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"
  err-command: "Invalid command. Use /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"

# Russian
ru:
  enable-effect: "Эффект включен"
  disable-effect: "Эффект выключен"

  menu-name: "Выбрать эффект"
  item-enable: "Включить этот эффект"
  item-disable: "Выключить этот эффект"

  unsupported-ver: "Вы используйте версию сервера ниже 1.21.4, эта функция недоступна"
  unsupported-name: "Недоступно на вашей версии"

  cherry: "Cherry"
  endrod: "Endrod"
  totem: "Totem"
  heart: "Heart"
  pale: "Pale"
  purple: "Purple"
  notes: "Notes"
  cloud: "Cloud"

  # Warning
  warning: "При использовании этого эффекта вы можете увидеть вспышки и размытие изображения."

  err-console: "Эту команду может отправлять только игрок"
  err-perms: "Вы не имейте прав для использования этой команды"
  err-args: "Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>>"
  err-command: "Неизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud>"