# SimpleEffects - https://github.com/karpen-dev/SimpleEffects

# Config version
# Don't change this parameter
config-version: 7.0

# For change color use ampersand and §
# Example &fHello or §fWorld

# Plugin language - ru, en, jp, be
lang: en

update:
  using: true
  msg: "&cYou do not have the latest version of the plugin installed. You can download the latest version at https://modrinth.com/plugin/simpleeffects"

# Separate rights
rights:
  using: false

  cherry: "karpen.simpleeffects.cherry"
  endrod: "karpen.simpleeffects.endrod"
  totem: "karpen.simpleeffects.totem"
  heart: "karpen.simpleeffects.heart"
  pale: "karpen.simpleeffects.pale"
  notes: "karpen.simpleeffects.notes"
  purple: "karpen.simpleeffects.purple"

  totem_spiral: "karpen.simpleefects.totem_spiral"
  endrod_spiral: "karpen.simpleefects.endrod_spiral"
  cherry_spiral: "karpen.simpleefects.cherry_spiral"
  pale_spiral: "karpen.simpleefects.pale_spiral"
  purple_spiral: "karpen.simpleefects.purple_spiral"
  note_spiral: "karpen.simpleefects.note_spiral"

# Messages

# The translation of the plugin is not perfect and may contain errors,
# I will be glad to receive feedback from X: https://x.com/akariyapl

# プラグインの翻訳は完璧ではなく、誤りが含まれている可能性があります。
# X: https://x.com/akariyapl からのフィードバックをお待ちしております。

# Перевод плагина не идеальный и может содержать ошибки,
# буду рад фитбеку X: https://x.com/akariyapl

# English
en:
  enable-effect: "&aEffect enabled"
  disable-effect: "&aEffect disabled"

  menu-name: "Select effect"
  item-enable: "&aEnable this effect"
  item-disable: "&cDisable this effect"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  note: "&3Notes"

  totem_spiral: "&eTotem spiral"
  endrod_spiral: "&fEndrod spiral"
  cherry_spiral: "&dCherry spiral"
  pale_spiral: "&8Pale spiral"
  purple_spiral: "&5Purple spiral"
  note_spiral: "&3 Note spiral"

  # Warning
  warning: "&cWhile using this effect you may see flashes and blurry images."

  err-console: "&cYou can't send this command"
  err-perms: "&cYou can't have permission for using this"
  err-args: "&cUsing /eff <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>>"
  err-command: "&cInvalid command. Use /eff <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>>"

# Japanese
jp:
  enable-effect: "&aエフェクト有効"
  disable-effect: "&a効果は無効です"

  menu-name: "エフェクトを選択"
  item-enable: "&aこの効果を有効にする"
  item-disable: "&cこの効果を無効にする"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  note: "&3Notes"

  totem_spiral: "&eTotem spiral"
  endrod_spiral: "&fEndrod spiral"
  cherry_spiral: "&dCherry spiral"
  pale_spiral: "&8Pale spiral"
  purple_spiral: "&5Purple spiral"
  note_spiral: "&3Note spiral"

  # Warning
  warning: "&cこの効果を使用すると、フラッシュやぼやけた画像が見える場合があります。"

  err-console: "&cこのコマンドは送信できません"
  err-perms: "&cこれを使用する権限がありません"
  err-args: "&c/eff を使用する <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>>"
  err-command: "&c無効なコマンドです。/eff <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>> を使用してください。"

# Russian
ru:
  enable-effect: "&aЭффект включен"
  disable-effect: "&aЭффект выключен"

  menu-name: "Выбрать эффект"
  item-enable: "&aВключить этот эффект"
  item-disable: "&cВыключить этот эффект"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  note: "&3Notes"

  totem_spiral: "&eTotem spiral"
  endrod_spiral: "&fEndrod spiral"
  cherry_spiral: "&dCherry spiral"
  pale_spiral: "&8Pale spiral"
  purple_spiral: "&5Purple spiral"
  note_spiral: "&3 Note spiral"

  # Warning
  warning: "&cПри использовании этого эффекта вы можете увидеть вспышки и размытие изображения."

  err-console: "&cЭту команду может отправлять только игрок"
  err-perms: "&cВы не имейте прав для использования этой команды"
  err-args: "&cИспользуйте /eff <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>>"
  err-command: "&cНеизвестная команда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | spiral <effect>>"

# Belarusian
be:
  enable-effect: "&aЭфект уключаны"
  disable-effect: "&aЭфект выключаны"

  menu-name: "Выбраць эфект"
  item-enable: "&aУключыць гэты эфект"
  item-disable: "&cВыключыць гэты эфект"

  cherry: "&dCherry"
  endrod: "&fEndrod"
  totem: "&eTotem"
  heart: "&cHeart"
  pale: "&8Pale"
  purple: "&5Purple"
  note: "&3Notes"

  totem_spiral: "&eTotem spiral"
  endrod_spiral: "&fEndrod spiral"
  cherry_spiral: "&dCherry spiral"
  pale_spiral: "&8Pale spiral"
  purple_spiral: "&5Purple spiral"
  note_spiral: "&3 Note spiral"

  # Warning
  warning: "&cПры выкарыстанні гэтага эфекту вы можаце выбліскі і размыццё малюнка."

  err-console: "&cГэту каманду можа адпрауляць толькі ігрок"
  err-perms: "&cВы не маеце прау для выкарыставання гэтай каманды"
  err-args: "&cВыкарыстовывайце /eff <cherry | endrod | totem | heart | pale | purple | note | cloud | spiral <effect>>"
  err-command: "&cНевядомая каманда. Используйте /eff <cherry | endrod | totem | heart | pale | purple | note | cloud | spiral <effect>>"