name: SimpleEffects
version: '1.1.2'
main: com.karpen.simpleEffects.SimpleEffects
api-version: '1.21'
commands:
  eff:
    usage: /eff <cherry | endrod | totem>
    description: Создает эффект
    permission: karpen.simpleEffects.eff
    permission-message: У вас недостаточно прав