name: SimpleEffects
version: '1.2-special'
main: com.karpen.simpleEffects.SimpleEffects
api-version: '1.21.4'
commands:
  eff:
    usage: /eff <cherry | endrod | totem | heart>
    description: Create effect
    permission: karpen.simpleEffects.eff
    permission-message: You don't have permission
  eff-reload:
    usage: /eff-reload
    description: Reload plugin
    permission: karpen.simpleEffects.reload
    permission-message: You don't have permission